### PR TITLE
fix: logger -> dlogger

### PR DESCRIPTION
**Pull request by hack3ric**
Recent version of dtkcore changed `logger`'s name to `dlogger`: https://github.com/linuxdeepin/dtkcore/commit/24a29a0f9f60a393e0b34f8b2b5d0ec9ea5bdcd1

### CODE REVIEW

**Comment by hack3ric** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Review by BLumia — APPROVED** [review]

**Comment by BLumia** [comment]
看上去同时需要 https://github.com/linuxdeepin/deepin-clone/pull/44 才能构建通过。修复本身是没问题的，可以合并。

**Pull request merged**
